### ISSUE TITLE
How to obtain real world hand position using VR contollers?

### ISSUE THREAD

**Issue by makselro** [BlankeLab/ExVR#1]
Hi,

I am developing a reachability estimation task and during a calibration routine, I need to measure the maximum reachable position for each participant. Is there a component that would allow this ?

I have the following equipment that could be used for that:

- HMD controller (oculus or vive) -> ideal solution, but I have not found a component for this
- mouse -> there is a mouse component and I can see the 2D mouse position, but could it be used to map a corresponding VR position ? seems complicated.

The idea would be to give the controller or mouse to the participant and he performs a fully extended reaching movement and I record this position. I will then use this position +/- a certain offset to display objects and the participant has to judge whether the objet is perceived as reachable or not.

Thank you in advance for the help.

**Comment by FlorianLance** [comment]
At the moment there is no dedicated Component for getting or displaying a VR controller, but you can easily retrieve their position using a bit of code from a CSharpFunction or a CSharpScript component:

```
// we retrieve the parent transform
var controllersTR = ExVR.Display().cameras().cameraRig.transform.Find("Controllers");

// from it we can get the two children (it can only manage two controllers for now)
var leftC = controllersTR.Find("Controller (left)");
var rightC = controllersTR.Find("Controller (right)");

// here you can get its position / rotation / euler angles
Vector3 leftControllerPosition = leftC .position;
```

Exemple by using a CSharpFunction component: 

![image](https://github.com/BlankeLab/ExVR/assets/1221777/a7873f32-86dc-4dcd-926a-68ab6608b00d)

If you want to retrieve the position at every frame you have to connect it to an Update node like I did.

You can also return the whole transform in the function:

![image](https://github.com/BlankeLab/ExVR/assets/1221777/8a4fa1a5-e946-417f-b3a0-b42727ee0932)

If you want to display it, you can use a model (or an asset bundle containing the real controller model) and update its coordinates:
![image](https://github.com/BlankeLab/ExVR/assets/1221777/96035867-e73a-456f-80a3-983c47eddeaa)


![image](https://github.com/BlankeLab/ExVR/assets/1221777/8a395ee1-903c-4b17-90d5-1a160678ebe1)
