### ISSUE TITLE
How to make a routine last forever until we end it with a button press

### ISSUE THREAD

**Issue by makselro** [BlankeLab/ExVR#2]
the title.

Thank you.

**Comment by FlorianLance** [comment]
You can achieve from several ways, the simplest option is to use the Connections panel.
After having created a Keyboard component and added it to the "Wait for input" routine, you can add its node ("Add node/Component/Keyboard") from the visual scripting part. 
Just link the keyboard to a "Check Keyboard button" node for choosing the relevant input and link it to a "Next routine" node.

The current maximum duration for a routine is around 27 hours, so you just have to choose a value big enough. 

![image](https://github.com/BlankeLab/ExVR/assets/1221777/de1b0934-0993-49db-94ff-fea684eddfef)

**Comment by makselro** [comment]
thank you. My question was whether there is a way to set the routine time to infinity, but 27 hours works too.

**Comment by FlorianLance** [comment]
For having a virtually infinite routine until you press space, you can also do that:

![image](https://github.com/BlankeLab/ExVR/assets/1221777/1f695544-b5c8-4a81-b699-95c2a4ed5691)
