### ISSUE TITLE
Move VR objects with keyboard

### ISSUE THREAD

**Issue by makselro** [BlankeLab/ExVR#3]
I would like to adjust the height of VR objects in the calibration phase to match the height perception of the participant.

I am thinking this can be achieved with the connections pannel:

1) get the VR object position as input
2) detect a button press
3) increment the position values depending on the button pressed
4) set the VR object position with the updated values

I cannot find a way to "get" the VR object position, so maybe it is not possible in this way (or I am missing something?).

The other solution I see is a c# sharp script that does the same thing.

What is the best way to achieve this ?

Thank you.

**Comment by makselro** [comment]
With this connection scheme I can move the VR object once:

![image](https://github.com/BlankeLab/ExVR/assets/105039653/a2c4d2ea-0a45-4a80-9277-dce3a9292ca7)

I don't think it's the good way.

So most likely a script is the best solution.

**Comment by FlorianLance** [comment]
By doing this you keep updating the Vec3 with the same value. 
You can achieve your goad by using a counter:

![image](https://github.com/BlankeLab/ExVR/assets/1221777/149a9be5-8d1c-4d30-93a6-603c11a491ca)

**Comment by FlorianLance** [comment]
You can also use a CSharpFunction component for doing the same thing:

![image](https://github.com/BlankeLab/ExVR/assets/1221777/a3876bc8-b64c-4dc5-b5dd-e6295a8c01ce)


![image](https://github.com/BlankeLab/ExVR/assets/1221777/62abac34-7caa-46a7-b928-390a1b832c26)

You just have to define a static variable in the Extra panel:

![image](https://github.com/BlankeLab/ExVR/assets/1221777/ece3ce6a-0fb6-4d62-a71a-8e8c7386bab0)

**Comment by makselro** [comment]
Thank you! The script functions perfectly for simple VR objects (for plane and cube at least).

How to adapt the script for "humanoïd avatar" ?
The components expects a str as input and I guess we have to deal with the targets.

Thanks in advance.

**Comment by makselro** [comment]
I would like to modify the CS function that moves a VR object to directly modify the config so that the changes remains in next routines. I saw this documentation for the cube component:

### Content:

// unity
using UnityEngine;

namespace Ex{
	public class CubeComponent : ExComponent{
		public override void update_from_current_config();
	}
}


### Samples:


// retrieve component 
var modelComponent = (CubeComponent)get("cube_component_name");
// or 
var modelComponent = get<CubeComponent>("cube_component_name");
// or if only one available
var modelComponent = get_first<CubeComponent>();

// change model current condition parameters
// # retrieve config
var modelConfig = modelComponent.current_config();    

// # change material color
modelConfig.set_color("color", Color.blue);
// # change material metallic value
modelConfig.set<float>("metallic", 0.5f);
// # change material smoothness value
modelConfig.set<float>("smoothness", 0.2f);   

// you can move/resize the model with:
// # a list of 3 Vector3 (postion,rotation,scale)
List<Vector3> listV = new List<Vector3>();
listV.Add(new Vector3(0,2f,0));  // position
listV.Add(new Vector3(30f,0,0)); // rotation
listV.Add(Vector3.one);          // scale
modelConfig.set_transform("transform", listV);

// # a TransformValue
TransformValue trV = new TransformValue();
trV.position = new Vector3(0,2f,0);
trV.rotation = Quaternion.Euler(new Vector3(30f,0,0));
trV.scale    = Vector3.one;
modelConfig.set_transform("transform", trV);

// # a Transform
Transform tr = someGameObject.transform;
modelConfig.set_transform("transform", tr);

// apply changes
modelComponent.update_from_current_config();



### Configs parameters:

// initialization config
var initC = init_config();
TransformValue trV = initC.get_transform("init_transform");
initC.get<float>("size");
initC.get<bool>("tranparent");

// condition config
var currentC = current_config();
TransformValue trV = currentC.get_transform("transform");
currentC.get_color("color");
currentC.get<float>("metallic");
currentC.get<float>("smoothness");

#####

How to us this syntax inside the CS function ?

If I just use:

var modelComponent = (CubeComponent)get("cube_component_name");

'get' is not recognized

if I add something like this in the extra section

using Ex.ExComponent
using CubeComponent

'using' is not recognized

I also tried the CS script component, but I don't understand how it works (adding elements, no scripting at all ?)

Thanks in advance.

**Comment by makselro** [comment]
this issue is fully resolved, thank you.
