### ISSUE TITLE
Update Model component transform from C# script

### ISSUE THREAD

**Issue by FlorianLance** [BlankeLab/ExVR#5]
I would like to modify the CS function that moves a VR object to directly modify the config so that the changes remains in next routines. I saw this documentation for the cube component:

### Content:

```
// unity
using UnityEngine;

namespace Ex{
	public class CubeComponent : ExComponent{
		public override void update_from_current_config();
	}
}
```

```

### Samples:


// retrieve component 
var modelComponent = (CubeComponent)get("cube_component_name");
// or 
var modelComponent = get<CubeComponent>("cube_component_name");
// or if only one available
var modelComponent = get_first<CubeComponent>();

// change model current condition parameters
// # retrieve config
var modelConfig = modelComponent.current_config();    

// # change material color
modelConfig.set_color("color", Color.blue);
// # change material metallic value
modelConfig.set<float>("metallic", 0.5f);
// # change material smoothness value
modelConfig.set<float>("smoothness", 0.2f);   

// you can move/resize the model with:
// # a list of 3 Vector3 (postion,rotation,scale)
List<Vector3> listV = new List<Vector3>();
listV.Add(new Vector3(0,2f,0));  // position
listV.Add(new Vector3(30f,0,0)); // rotation
listV.Add(Vector3.one);          // scale
modelConfig.set_transform("transform", listV);

// # a TransformValue
TransformValue trV = new TransformValue();
trV.position = new Vector3(0,2f,0);
trV.rotation = Quaternion.Euler(new Vector3(30f,0,0));
trV.scale    = Vector3.one;
modelConfig.set_transform("transform", trV);

// # a Transform
Transform tr = someGameObject.transform;
modelConfig.set_transform("transform", tr);

// apply changes
modelComponent.update_from_current_config();

### Configs parameters:

// initialization config
var initC = init_config();
TransformValue trV = initC.get_transform("init_transform");
initC.get<float>("size");
initC.get<bool>("tranparent");

// condition config
var currentC = current_config();
TransformValue trV = currentC.get_transform("transform");
currentC.get_color("color");
currentC.get<float>("metallic");
currentC.get<float>("smoothness");

#####
```

How to us this syntax inside the CS function ?

If I just use:

`var modelComponent = (CubeComponent)get("cube_component_name");`

'get' is not recognized

if I add something like this in the extra section

```
using Ex.ExComponent
using CubeComponent

```
'using' is not recognized

I also tried the CS script component, but I don't understand how it works (adding elements, no scripting at all ?)

Thanks in advance.

_Originally posted by @makselro in https://github.com/BlankeLab/ExVR/issues/3#issuecomment-1742783134_

**Comment by FlorianLance** [comment]
You are doing a mix between C# function and C# script components.
C# function is mostly for creating small utility function for doing the glue between nodes and others scripts.
C# script have may more functionalities:

For using them you have to click on the "Display resources manager" button or from the menu ("Resources/Display resources manager")
![image](https://github.com/BlankeLab/ExVR/assets/1221777/7ce9a2ae-702a-4e43-b248-cd17c56e466f)


Click on the C# script panel, and from this place you can either add a previously created C# script or to create a new one using the "Generate script" button.

By doing the later, it open a popup window:
![image](https://github.com/BlankeLab/ExVR/assets/1221777/b5f0944b-7849-4990-8f8c-03c4e8ee87e4)
You have to choose the component name (you will have to refer by this name from the C# script component later)

Once the destination validated, you can open it by clicking on "Open file", (it will use the default editor for .cs files, so if you have installed Visual studio it will be opened with it)

Once open you will be able to seen a bunch of functions  you can comment or uncomment, every component in ExVR is using theses functions:
![image](https://github.com/BlankeLab/ExVR/assets/1221777/01674884-92b5-4fd8-9330-196861ea0da7)

Below you can see the documentation of the main classes inherited by the script.

You now have to reference your script component by setting its name:
![image](https://github.com/BlankeLab/ExVR/assets/1221777/08d427b2-ab73-44d9-ac7b-d3958d98f910)


So if you use the code you wrote inside the **initialize** or  the **start_routine** functions for example and if you have a Cube component in your scene named "cube_component_name", it will now work.

```
public override bool initialize() {

      var modelComponent = (CubeComponent)get("cube_component_name");
      log_message(modelComponent.name);

      return true; 
 }
```

It's because the **TemplateComponent** we just created is inheriting from **BaseCompiledCSharpComponent** and contains a lot of quality of life functionnalites.

**Comment by FlorianLance** [comment]
One important thing regarding transforms with model components:
![image](https://github.com/BlankeLab/ExVR/assets/1221777/7cfe8556-8256-43fa-a220-99c9d36ef180)

From the **initialization config** panel, the transform will be only applied once (except if you check **Do not apply**) when you load the experiment by clicking on one of theses buttons:

![image](https://github.com/BlankeLab/ExVR/assets/1221777/e52e43cd-1cfa-4c22-a805-065a4a61fdb7)

But from the **Conditions configs** panel:

![image](https://github.com/BlankeLab/ExVR/assets/1221777/dae40729-31b3-4598-a5a9-6910e1c5fffe)

Each time you start a routine with a condition referencing this component config, it will apply the **Config transform**, except if you check `Do not apply`.

So if you wish to control the transform of this component only from scripting or visual scripting, I encourage you to check the **Do not apply** button at least for the **Conditions config** panel.

After from you script you can use either of theses methods to update the component position:
```
// you can move/resize the model with:
// # a list of 3 Vector3 (postion,rotation,scale)
List<Vector3> listV = new List<Vector3>();
listV.Add(new Vector3(0,2f,0));  // position
listV.Add(new Vector3(30f,0,0)); // rotation
listV.Add(Vector3.one);          // scale
modelConfig.set_transform("transform", listV);

// # a TransformValue
TransformValue trV = new TransformValue();
trV.position = new Vector3(0,2f,0);
trV.rotation = Quaternion.Euler(new Vector3(30f,0,0));
trV.scale    = Vector3.one;
modelConfig.set_transform("transform", trV);

// # a Transform
Transform tr = someGameObject.transform;
modelConfig.set_transform("transform", tr);

// apply changes
modelComponent.update_from_current_config();`
```

So your final script may be like this:
```

// system
using System;
using System.Reflection;
using System.Collections.Generic;

// unity
using UnityEngine;

namespace Ex{

    public class TemplateComponent : BaseCompiledCSharpComponent{

        CubeComponent cube = null;

        // Ex component flow functions, uncomment to use
        // # once per loading
        public override bool initialize() {
            cube = (CubeComponent)get("cube_component_name");
            return true; 
        }
     
        public override void update() {

            // # a TransformValue
            TransformValue trV = new TransformValue();
            trV.position = new Vector3(..., ..., ...);
            trV.rotation = Quaternion.Euler(new Vector3(..., ..., ...));
            trV.scale = Vector3.one;

            cube.current_config().set_transform("transform", trV);

        }
    }
}

```

**Comment by FlorianLance** [comment]
The template file generated by the component is a bit out of date, I'll update it.

**Comment by makselro** [comment]
Thank you for the amazing support.

Below is my attempt to read the keyboard input from slot 5:

####################
// system
using System;
using System.Reflection;
using System.Collections.Generic;

// unity
using UnityEngine;

namespace Ex{

    public class CS_move_cube : BaseCompiledCSharpComponent{

        CubeComponent Cube = null;
        // Ex component flow functions, uncomment to use
        // # once per loading
        public override bool initialize() {
            Cube = (CubeComponent)get("Cube");
            return true;
        }
     
        public override void update() {
            
            var CubeConfig = Cube.current_config();
            Vector3 CubePos = CubeConfig.get<Vector3>("position");
            float CubeHeight = CubePos.y;
            
            var idV = (IdAny)slot5;

            if(idV.id == 0){
                CubeHeight += 0.1f;
            }else if(idV.id == 1){
                CubeHeight -= 0.1f; 
            }
                       
            // # a TransformValue
            TransformValue trV = new TransformValue();
            trV.position = new Vector3(CubePos.x, CubeHeight, CubePos.z);
            trV.rotation = Quaternion.Euler(new Vector3(0, 0, 0));
            trV.scale = Vector3.one;

            Cube.current_config().set_transform("transform", trV);

        }       
    }
}

################

I get the following error:

[COMPILER] Compilation error CS0428 : "Cannot convert method group `slot5' to non-delegate type `Ex.IdAny'. Consider using parentheses to invoke the method" from file D:/Michel/ExVR/PPS_reaching/assets/CS_move_cube.cs at line 27 and column 25

################
The connections:

![image](https://github.com/BlankeLab/ExVR/assets/105039653/fb85f3e4-2ad5-487d-8215-b7defb1bd076)

###############

An alternative would be the read directly the keyboard within the script. If this would be the preferred way, what is the correct way to "catch" the latest pressed key ? last_event() or send_infos_and_signals()
