### ISSUE TITLE
How to read Keyboard input from C# script using nodes

### ISSUE THREAD

**Issue by FlorianLance** [BlankeLab/ExVR#6]
Thank you for the amazing support.
Below is my attempt to read the keyboard input from slot 5:

    ####################
    // system
    using System;
    using System.Reflection;
    using System.Collections.Generic;
    
    // unity
    using UnityEngine;
    
    namespace Ex{

    public class CS_move_cube : BaseCompiledCSharpComponent{

        CubeComponent Cube = null;
        // Ex component flow functions, uncomment to use
        // # once per loading
        public override bool initialize() {
            Cube = (CubeComponent)get("Cube");
            return true;
        }
     
        public override void update() {
            
            var CubeConfig = Cube.current_config();
            Vector3 CubePos = CubeConfig.get<Vector3>("position");
            float CubeHeight = CubePos.y;
            
            var idV = (IdAny)slot5;

            if(idV.id == 0){
                CubeHeight += 0.1f;
            }else if(idV.id == 1){
                CubeHeight -= 0.1f; 
            }
                       
            // # a TransformValue
            TransformValue trV = new TransformValue();
            trV.position = new Vector3(CubePos.x, CubeHeight, CubePos.z);
            trV.rotation = Quaternion.Euler(new Vector3(0, 0, 0));
            trV.scale = Vector3.one;

            Cube.current_config().set_transform("transform", trV);

        }       
    }
}

################

I get the following error:

**[COMPILER] Compilation error CS0428 : "Cannot convert method group `slot5' to non-delegate type `Ex.IdAny'. Consider using parentheses to invoke the method" from file D:/Michel/ExVR/PPS_reaching/assets/CS_move_cube.cs at line 27 and column 25**

################
The connections:

![image](https://github.com/BlankeLab/ExVR/assets/105039653/fb85f3e4-2ad5-487d-8215-b7defb1bd076)

###############

An alternative would be the read directly the keyboard within the script. If this would be the preferred way, what is the correct way to "catch" the latest pressed key ? last_event() or send_infos_and_signals()

_Originally posted by @makselro in https://github.com/BlankeLab/ExVR/issues/5#issuecomment-1744596967_

**Comment by FlorianLance** [comment]
If you want to retrieve data from a script using nodes, you have to uncomment the corresponding slots functions from the code,
in your case you are using the slot n°5, (you could have used even the others with an IdAny, by using the slot 5 it is already converted, it's a small convenience)

        // # slots
        public override void slot1(object value) { 
        
        }
        //public override void slot2(object value) { }
        //public override void slot3(object value) { }
        //public override void slot4(object value) { }
        public override void slot5(IdAny idValue) {
            int id = idValue.id;
            object value = idValue.value;
        }


So your class will look like this:

```

// system
using System;
using System.Reflection;
using System.Collections.Generic;

// unity
using UnityEngine;

namespace Ex {

    public class CS_move_cube : BaseCompiledCSharpComponent {

        CubeComponent Cube = null;
        Vector3 currentCubePosition = new Vector3();
        // Ex component flow functions, uncomment to use
        // # once per loading
        public override bool initialize() {
            Cube = (CubeComponent)get("Cube");
            return true;
        }

        public override void start_routine() {

            // we retrieve the position of the cube at the beginning of the routine
            var currentC = Cube.current_config();
            // there was a typo in the doc, if we want a TransformValue we need to call "get_transform_value" and not "get_transform"
            TransformValue trV = currentC.get_transform_value("transform");
            currentCubePosition = trV.position;
        }

        public override void slot5(IdAny idValue) {

            // this function is called everytime a value is passed throught the slot n°5 of the script node

            int id = idValue.id;
            //object value = idValue.value; // we don't use the value part of IdAny
            if (id == 0) { // we increment or decrement the height according to the input id                
                currentCubePosition.y = currentCubePosition.y + 0.1f;
                log_message("Move cube UP! " + Converter.to_string(currentCubePosition));
            } else if (id == 1) {
                currentCubePosition.y = currentCubePosition.y - 0.1f;
                log_message("Move cube DOWN! " + Converter.to_string(currentCubePosition));
            }

            // we update the cube current config transform
            TransformValue trV = new TransformValue();
            trV.position = currentCubePosition;
            trV.rotation = Quaternion.Euler(new Vector3(0, 0, 0));
            trV.scale    = Vector3.one;
            Cube.current_config().set_transform("transform", trV);
            Cube.update_from_current_config(); // important, we need to call this in order to the changed to be taken into account
        }
    }
}

```

![image](https://github.com/BlankeLab/ExVR/assets/1221777/aaae15a7-1ba1-450f-80d8-c13730b9e4f4)

**Comment by makselro** [comment]
Thank you! This issue can be closed on my side.
